### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by hansmbakker** [getsenic/nuimo-windows#11]
It would be nice to have a coding style guideline that would be easy to check for before committing. This would let people make less mistakes so that PRs can be merged quicker. I believe in other languages this is called linting.

One way how to do that is to use StyleCop (free) or ReSharper (paid) to enforce these rules.

A settings file for such a tool, much like a file for CI settings or gitignore settings, can be put in the repo to let everybody use the same rules.

One start could be to use the default StyleCop rules.

What do you think?

**Comment by larsblumberg** [comment]
While coding style guides and linting are nice to have, we have no resources right now to set these up. Furthermore I don't expect this SDK to change a lot in the long run.

Feel free to submit a PR that enables/enforces linting.
